In [2]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [25]:
df = pd.read_csv('DataScience_salaries_2025.csv')

df.shape
print(df['experience_level'].unique()) # cardinality of 4
print(df['company_size'].unique()) # cardinality of 3
len(df['job_title'].unique())

['MI' 'SE' 'EN' 'EX']
['M' 'L' 'S']

317

In [26]:
print(df.duplicated().sum())                 # count of fully-identical rows
df[df.duplicated(keep=False)].sort_values(list(df.columns)).head(20)

46960

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
93444,2021,EN,FT,Data Scientist,90000,USD,90000,US,100,US,S
93519,2021,EN,FT,Data Scientist,90000,USD,90000,US,100,US,S
93359,2021,MI,FT,Data Engineer,200000,USD,200000,US,100,US,L
93439,2021,MI,FT,Data Engineer,200000,USD,200000,US,100,US,L
93515,2021,MI,FT,Data Scientist,76760,EUR,90734,DE,50,DE,L
93553,2021,MI,FT,Data Scientist,76760,EUR,90734,DE,50,DE,L
90666,2021,MI,FT,Data Scientist,150000,USD,150000,US,100,US,M
93385,2021,MI,FT,Data Scientist,150000,USD,150000,US,100,US,M
91902,2022,EN,FT,Data Analyst,50000,USD,50000,US,50,US,L
91919,2022,EN,FT,Data Analyst,50000,USD,50000,US,50,US,L
92324,2022,EN,FT,Data Engineer,40000,GBP,49253,GB,100,GB,M
93132,2022,EN,FT,Data Engineer,40000,GBP,49253,GB,100,GB,M
91753,2022,EN,FT,Data Engineer,135000,USD,135000,US,0,US,M
91876,2022,EN,FT,Data Engineer,135000,USD,135000,US,0,US,M
91962,2022,EN,FT,Data Engineer,135000,USD,135000,US,0,US,M
92070,2022,EN,FT,Data Engineer,135000,USD,135000,US,0,US,M
92143,2022,EN,FT,Data Engineer,135000,USD,135000,US,0,US,M
92224,2022,EN,FT,Data Engineer,135000,USD,135000,US,0,US,M
91752,2022,EN,FT,Data Engineer,160000,USD,160000,US,0,US,M
91875,2022,EN,FT,Data Engineer,160000,USD,160000,US,0,US,M

In [8]:
df.head()

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2025,MI,FT,Research Scientist,208000,USD,208000,US,0,US,M
1,2025,MI,FT,Research Scientist,147000,USD,147000,US,0,US,M
2,2025,SE,FT,Research Scientist,173000,USD,173000,US,0,US,M
3,2025,SE,FT,Research Scientist,117000,USD,117000,US,0,US,M
4,2025,MI,FT,AI Engineer,100000,USD,100000,US,100,US,M

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93597 entries, 0 to 93596
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   work_year           93597 non-null  int64
 1   experience_level    93597 non-null  object
 2   employment_type     93597 non-null  object
 3   job_title           93597 non-null  object
 4   salary              93597 non-null  int64
 5   salary_currency     93597 non-null  object
 6   salary_in_usd       93597 non-null  int64
 7   employee_residence  93597 non-null  object
 8   remote_ratio        93597 non-null  int64
 9   company_location    93597 non-null  object
 10  company_size        93597 non-null  object
dtypes: int64(4), object(7)
memory usage: 7.9+ MB

This below cell is for my own curiosity, but these salaries seem really, really high

In [15]:
df=df[(df["experience_level"] == "EN") & (df["employment_type"] == "FT") & (df['employee_residence'] == 'US')]
df.drop(columns=['experience_level','employment_type','employee_residence'])

,work_year,job_title,salary,salary_currency,salary_in_usd,remote_ratio,company_location,company_size
10,2025,Business Intelligence Developer,76000,USD,76000,0,US,M
11,2025,Business Intelligence Developer,76000,USD,76000,0,US,M
14,2025,Data Scientist,120000,USD,120000,100,US,M
15,2025,Data Scientist,100000,USD,100000,100,US,M
32,2025,Data Analyst,86100,USD,86100,0,US,M
...,...,...,...,...,...,...,...,...
93478,2021,Data Scientist,100000,USD,100000,100,US,M
93483,2020,Data Analyst,72000,USD,72000,100,US,L
93517,2021,Machine Learning Engineer,81000,USD,81000,50,US,S
93519,2021,Data Scientist,90000,USD,90000,100,US,S
93594,2020,Data Scientist,105000,USD,105000,100,US,S

there are no null values within this dataset, it's from kaggle so this isn't too surprising

In [16]:
df.isnull().sum()

work_year             0
experience_level      0
employment_type       0
job_title             0
salary                0
salary_currency       0
salary_in_usd         0
employee_residence    0
remote_ratio          0
company_location      0
company_size          0
dtype: int64

Job title shows high cardinality but also a bias towards Data analyst roles, which makes sense as it's from a data analyst salary dataset

In [18]:
df['job_title'].value_counts().head(30)

job_title
Data Analyst                       2730
Analyst                             606
Data Scientist                      495
Software Engineer                   383
Data Engineer                       326
Machine Learning Engineer           316
Engineer                            304
Research Scientist                  276
Research Analyst                    182
Business Intelligence Analyst       168
Business Analyst                     82
Data Management Analyst              76
Research Engineer                    76
Applied Scientist                    60
Data Specialist                      54
Associate                            47
Data Quality Analyst                 44
Product Analyst                      42
Consultant                           38
Data Operations Analyst              38
Software Development Engineer        38
Data Governance Analyst              36
Analytics Engineer                   36
BI Analyst                           35
Business Intelligence Developer      30
Developer                            30
Data Reporting Analyst               28
AI Engineer                          27
Manager                              24
Insight Analyst                      24
Name: count, dtype: int64

['EN']